# Generated by Django 4.2.3 on 2023-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodule', '0002_alter_mainmodule_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodule',
            name='division',
            field=models.CharField(choices=[('0', 'Overview Panel'), ('1', 'Operations'), ('2', 'Management Tools')], default='2', max_length=1),
        ),
    ]
