# Generated by Django 4.2.3 on 2023-07-16 17:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(max_length=250)),
                ('segment', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('django_content_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='django_content_type_id', to='contenttypes.contenttype', validators=[django.core.validators.MinValueValidator(1)])),
                ('entered_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_entered', to=settings.AUTH_USER_MODEL)),
                ('mainmodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainmodule_id', to='mainmodule.mainmodule', validators=[django.core.validators.MinValueValidator(1)])),
                ('modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module',
                'ordering': ['-pk'],
            },
        ),
    ]
