# Generated by Django 4.2.3 on 2023-10-10 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cas', '0003_cas_submit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datatransmission_cas', to='cas.cas')),
                ('transfer_status', models.CharField(choices=[('0', 'Failure'), ('1', 'Success')], default='1', max_length=1)),
                ('ref_submit_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('acknowledgement_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('response_datetime', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('system_configuration_mode', models.CharField(default='', max_length=20)),
                ('transmitted_date', models.DateTimeField(auto_now_add=True)),
                ('transmitted_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datatransmission_transmitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_datatransmission',
            },
        ),
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(default='', max_length=255)),
                ('session_key', models.CharField(default='', max_length=255)),
                ('token_expiry', models.CharField(default='', max_length=50)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Model',
                'verbose_name_plural': 'Token Model',
                'db_table': 'portal_token',
            },
        ),
        migrations.CreateModel(
            name='InquiryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatransmission', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiryresult_datatransmission', to='datatransmission.datatransmission')),
                ('transfer_status', models.CharField(choices=[('0', 'Failure'), ('1', 'Success')], default='1', max_length=1)),
                ('acknowledgement_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('response_datetime', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('process_status_code', models.CharField(blank=True, choices=[('01', 'Processing completed'), ('02', 'In processing'), ('03', 'Unable to process')], default='', max_length=50, null=True)),
                ('result_status_code', models.CharField(blank=True, choices=[('SUC001', 'Success'), ('SYN002', 'Invalid signature'), ('SYN003', 'Duplicated EisUniqueId'), ('SYN004', 'e-invoice schema error'), ('ERR001', 'Seller TIN error'), ('ERR002', 'Issuance datetime error'), ('ERR003', 'Transmission datetime error'), ('ERR004', 'Total Sales Amount, VAT Amount error'), ('ERR005', 'Code type error'), ('ERR006', 'Accreditation ID error'), ('ERR007', 'E-invoice Unique ID to be corrected error'), ('ERR999', 'Other undefined error')], default='', max_length=50, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('inquired_date', models.DateTimeField(auto_now_add=True)),
                ('inquired_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datatransmission_inquired', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_inquiryresult',
            },
        ),
    ]
