# Generated by Django 4.2.3 on 2023-09-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransmissionModel',
            fields=[
                ('cas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cas.cas')),
                ('transfer_status', models.CharField(choices=[('P', 'Processing'), ('T', 'Transmitted'), ('F', 'Failed')], default='A', max_length=1)),
            ],
            bases=('cas.cas',),
        ),
    ]
