# Generated by Django 4.2.3 on 2023-09-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datatransmission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datatransmissionmodel',
            table='portal_datatransmission',
        ),
    ]
