# Generated by Django 4.2.3 on 2023-10-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0003_cas_submit_id'),
        ('datatransmission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransmission',
            name='cas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datatransmission_cas', to='cas.cas'),
        ),
    ]
