# Generated by Django 4.2.3 on 2023-09-27 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datatransmission', '0002_alter_datatransmissionmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(default='', max_length=255)),
                ('session_key', models.CharField(default='', max_length=255)),
                ('token_expiry', models.CharField(default='', max_length=50)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Model',
                'verbose_name_plural': 'Token Model',
                'db_table': 'portal_token',
            },
        ),
    ]
