# Generated by Django 4.2.3 on 2023-07-23 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('address_1', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('address_2', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('address_3', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('telephone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('tin_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('logo', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('entered_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_entered', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company',
                'ordering': ['-pk'],
            },
        ),
    ]
