# Generated by Django 4.2.3 on 2023-07-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_invoice_number', models.CharField(max_length=50, verbose_name='Company SI/OR/SB/DM/CM No.')),
                ('issue_date', models.CharField(max_length=8, verbose_name='SI/OR/SB/DM/CM Issuance Date - YYYYMMDD')),
                ('eis_unique_id', models.CharField(max_length=24, verbose_name='BIR e-invoice Unique ID')),
                ('document_type', models.CharField(choices=[('01', 'Sales Invoice (SI)'), ('02', 'Debit Memo (DM)'), ('03', 'Credit Memo (CM)'), ('04', 'Service Billing (SB / Billing Statement)'), ('05', 'Official Reciept (OR)')], max_length=2, verbose_name='Document Type')),
                ('transaction_classification', models.CharField(choices=[('01', 'VATable'), ('02', 'Zero-Rated'), ('03', 'VAT Exempt')], max_length=2, verbose_name='Transaction Classification')),
                ('is_correction', models.CharField(choices=[('Y', 'Yes'), ('N', 'Not')], max_length=1, verbose_name='Correction Yes or Not')),
                ('correction_code', models.CharField(blank=True, choices=[('01', 'Error'), ('02', 'Duplication'), ('03', 'Addition/reduction'), ('04', 'Cancellation'), ('05', 'Return'), ('09', 'Others')], max_length=2, null=True, verbose_name='e-Invoice Correction Code')),
                ('previous_unique_id', models.CharField(blank=True, max_length=24, null=True, verbose_name='E-Invoice Unique ID of the document to be corrected')),
                ('remarks_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remarks1')),
                ('seller_info_tin', models.CharField(default='000000000', max_length=9, verbose_name='Seller TIN')),
                ('seller_info_branch_code', models.CharField(default='00000', max_length=5, verbose_name='Seller Branch Code')),
                ('seller_info_type', models.CharField(choices=[('0', 'VAT registered'), ('1', 'Non-VAT registered')], max_length=1, verbose_name='Seller Type')),
                ('seller_info_registered_name', models.CharField(max_length=200, verbose_name='Seller Registered Name')),
                ('seller_info_business_name', models.CharField(max_length=200, verbose_name='Seller Business Name/Trade Name')),
                ('seller_info_email', models.CharField(blank=True, default='null', max_length=100, null=True, verbose_name='Seller Email address')),
                ('seller_info_registered_address', models.CharField(max_length=300, verbose_name='Seller Registered Address')),
                ('buyer_info_tin', models.CharField(default='000000000', max_length=9, verbose_name='Buyer TIN')),
                ('buyer_info_branch_code', models.CharField(default='00000', max_length=5, verbose_name='Buyer Branch Code')),
                ('buyer_info_registered_name', models.CharField(max_length=200, verbose_name='Buyer Registered Name')),
                ('buyer_info_business_name', models.CharField(max_length=200, verbose_name='Buyer Business Name/Trade Name')),
                ('buyer_info_email', models.CharField(blank=True, default='null', max_length=100, null=True, verbose_name='Buyer Email address')),
                ('buyer_info_registered_address', models.CharField(blank=True, default='null', max_length=300, null=True, verbose_name='Buyer Registered Address')),
                ('buyer_info_delivery_address', models.CharField(blank=True, default='null', max_length=300, null=True, verbose_name='Buyer Delivery Address')),
                ('buyer_info_airway_bill_number', models.CharField(blank=True, default='null', max_length=50, null=True, verbose_name='Airway Bill Number')),
                ('buyer_info_airway_bill_number_date', models.CharField(blank=True, default='null', max_length=8, null=True, verbose_name='Airway Bill Number Date')),
                ('buyer_info_bill_of_lading_number', models.CharField(blank=True, default='null', max_length=50, null=True, verbose_name='Bill of Lading Number')),
                ('buyer_info_bill_of_lading_number_date', models.CharField(blank=True, default='null', max_length=8, null=True, verbose_name='Bill of Lading Number Date')),
                ('item_list_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('item_list_description', models.CharField(default='null', max_length=100, verbose_name='Item Description/Service')),
                ('item_list_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Item Quantity')),
                ('item_list_unit_of_measure', models.CharField(blank=True, default='null', max_length=50, null=True, verbose_name='Item Unit of measure')),
                ('item_list_unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Unit Cost')),
                ('item_list_sales_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Item Sales Amount')),
                ('item_list_regular_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Regular Discount Amount')),
                ('item_list_special_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Special Discount Amount')),
                ('item_list_net_of_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Net of Item Sales')),
                ('item_list_total_net_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Total of Net of Item Sales')),
                ('senior_citizen_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Senior Citizen Discount Amount')),
                ('pwd_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='PWD Discount Amount')),
                ('regular_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Regular Discount Amount')),
                ('special_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Special Discount Amount')),
                ('remarks_2', models.CharField(blank=True, default='null', max_length=500, null=True, verbose_name='Remarks2 - Brief explanation of discount if needed')),
                ('other_tax_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Other Taxable Revenue')),
                ('total_net_sales_after_discounts', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Total Net Sales After Discounts')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='VAT Amount')),
                ('withholding_tax_income_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Withholding Tax-Income Tax')),
                ('withholding_tax_business_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Withholding Tax-Business VAT')),
                ('withholding_tax_business_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Withholding Tax-Business Percentage')),
                ('other_non_taxable_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Other Non-Taxable Charges')),
                ('net_amount_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=28, verbose_name='Net Amount Payable')),
                ('currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Currency')),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=28, null=True, verbose_name='Conversion Rate')),
                ('forex_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=28, null=True, verbose_name='Currency Amount')),
                ('ptu_number', models.CharField(max_length=50, verbose_name='PTU Number/Acknowledgment Certificate Control Number')),
                ('ptu_expiry_date', models.CharField(max_length=8, verbose_name='Expiry Date of PTU')),
                ('cas_type', models.CharField(choices=[('01', 'iES Advertising'), ('02', 'Circulation')], max_length=2, verbose_name='CAS Type - Advertising/Circulation')),
                ('item_id', models.IntegerField(verbose_name='Transaction item ID or primary key')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('entered_by', models.IntegerField(default=1)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(default=1)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cas',
                'ordering': ['-pk'],
            },
        ),
    ]
