# Generated by Django 4.2.3 on 2023-09-22 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eiscredential', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eiscredential',
            name='entered_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eiscredential_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eiscredential',
            name='modified_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eiscredential_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
