# Generated by Django 4.2.3 on 2023-09-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiscredential', '0003_alter_eiscredential_access_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eiscredential',
            name='authorization_url',
        ),
        migrations.AddField(
            model_name='eiscredential',
            name='authentication_url',
            field=models.CharField(default='', max_length=255, verbose_name='Authentication URL'),
        ),
        migrations.AlterField(
            model_name='eiscredential',
            name='inquiry_result_url',
            field=models.CharField(default='', max_length=255, verbose_name='Inquiry Result URL'),
        ),
        migrations.AlterField(
            model_name='eiscredential',
            name='invoices_url',
            field=models.CharField(default='', max_length=255, verbose_name='Invoices URL'),
        ),
    ]
