# Generated by Django 4.2.3 on 2023-09-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiscredential', '0004_remove_eiscredential_authorization_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eiscredential',
            name='jws_private_key',
            field=models.CharField(default='', max_length=20, verbose_name='JWS Private Key'),
        ),
    ]
